language: node_js

node_js:
  - 8

install:
  - npm install

branches:
  only:
    - develop

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: develop
